/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type VenueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "venue";
};

export type ArtistReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "artist";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  eventType?: "in-person" | "virtual";
  date?: string;
  doorsOpen?: number;
  venue?: VenueReference;
  headline?: ArtistReference;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tickets?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  city?: string;
  country?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AvailabilityDuration = {
  _type: "availabilityDuration";
  from?:
    | "12:00 AM"
    | "12:15 AM"
    | "12:30 AM"
    | "12:45 AM"
    | "1:00 AM"
    | "1:15 AM"
    | "1:30 AM"
    | "1:45 AM"
    | "2:00 AM"
    | "2:15 AM"
    | "2:30 AM"
    | "2:45 AM"
    | "3:00 AM"
    | "3:15 AM"
    | "3:30 AM"
    | "3:45 AM"
    | "4:00 AM"
    | "4:15 AM"
    | "4:30 AM"
    | "4:45 AM"
    | "5:00 AM"
    | "5:15 AM"
    | "5:30 AM"
    | "5:45 AM"
    | "6:00 AM"
    | "6:15 AM"
    | "6:30 AM"
    | "6:45 AM"
    | "7:00 AM"
    | "7:15 AM"
    | "7:30 AM"
    | "7:45 AM"
    | "8:00 AM"
    | "8:15 AM"
    | "8:30 AM"
    | "8:45 AM"
    | "9:00 AM"
    | "9:15 AM"
    | "9:30 AM"
    | "9:45 AM"
    | "10:00 AM"
    | "10:15 AM"
    | "10:30 AM"
    | "10:45 AM"
    | "11:00 AM"
    | "11:15 AM"
    | "11:30 AM"
    | "11:45 AM"
    | "12:00 PM"
    | "12:15 PM"
    | "12:30 PM"
    | "12:45 PM"
    | "1:00 PM"
    | "1:15 PM"
    | "1:30 PM"
    | "1:45 PM"
    | "2:00 PM"
    | "2:15 PM"
    | "2:30 PM"
    | "2:45 PM"
    | "3:00 PM"
    | "3:15 PM"
    | "3:30 PM"
    | "3:45 PM"
    | "4:00 PM"
    | "4:15 PM"
    | "4:30 PM"
    | "4:45 PM"
    | "5:00 PM"
    | "5:15 PM"
    | "5:30 PM"
    | "5:45 PM"
    | "6:00 PM"
    | "6:15 PM"
    | "6:30 PM"
    | "6:45 PM"
    | "7:00 PM"
    | "7:15 PM"
    | "7:30 PM"
    | "7:45 PM"
    | "8:00 PM"
    | "8:15 PM"
    | "8:30 PM"
    | "8:45 PM"
    | "9:00 PM"
    | "9:15 PM"
    | "9:30 PM"
    | "9:45 PM"
    | "10:00 PM"
    | "10:15 PM"
    | "10:30 PM"
    | "10:45 PM"
    | "11:00 PM"
    | "11:15 PM"
    | "11:30 PM"
    | "11:45 PM";
  to?:
    | "12:00 AM"
    | "12:15 AM"
    | "12:30 AM"
    | "12:45 AM"
    | "1:00 AM"
    | "1:15 AM"
    | "1:30 AM"
    | "1:45 AM"
    | "2:00 AM"
    | "2:15 AM"
    | "2:30 AM"
    | "2:45 AM"
    | "3:00 AM"
    | "3:15 AM"
    | "3:30 AM"
    | "3:45 AM"
    | "4:00 AM"
    | "4:15 AM"
    | "4:30 AM"
    | "4:45 AM"
    | "5:00 AM"
    | "5:15 AM"
    | "5:30 AM"
    | "5:45 AM"
    | "6:00 AM"
    | "6:15 AM"
    | "6:30 AM"
    | "6:45 AM"
    | "7:00 AM"
    | "7:15 AM"
    | "7:30 AM"
    | "7:45 AM"
    | "8:00 AM"
    | "8:15 AM"
    | "8:30 AM"
    | "8:45 AM"
    | "9:00 AM"
    | "9:15 AM"
    | "9:30 AM"
    | "9:45 AM"
    | "10:00 AM"
    | "10:15 AM"
    | "10:30 AM"
    | "10:45 AM"
    | "11:00 AM"
    | "11:15 AM"
    | "11:30 AM"
    | "11:45 AM"
    | "12:00 PM"
    | "12:15 PM"
    | "12:30 PM"
    | "12:45 PM"
    | "1:00 PM"
    | "1:15 PM"
    | "1:30 PM"
    | "1:45 PM"
    | "2:00 PM"
    | "2:15 PM"
    | "2:30 PM"
    | "2:45 PM"
    | "3:00 PM"
    | "3:15 PM"
    | "3:30 PM"
    | "3:45 PM"
    | "4:00 PM"
    | "4:15 PM"
    | "4:30 PM"
    | "4:45 PM"
    | "5:00 PM"
    | "5:15 PM"
    | "5:30 PM"
    | "5:45 PM"
    | "6:00 PM"
    | "6:15 PM"
    | "6:30 PM"
    | "6:45 PM"
    | "7:00 PM"
    | "7:15 PM"
    | "7:30 PM"
    | "7:45 PM"
    | "8:00 PM"
    | "8:15 PM"
    | "8:30 PM"
    | "8:45 PM"
    | "9:00 PM"
    | "9:15 PM"
    | "9:30 PM"
    | "9:45 PM"
    | "10:00 PM"
    | "10:15 PM"
    | "10:30 PM"
    | "10:45 PM"
    | "11:00 PM"
    | "11:15 PM"
    | "11:30 PM"
    | "11:45 PM";
};

export type AvailabilityDay = {
  _type: "availabilityDay";
  day?:
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday";
  availableTimes?: Array<
    {
      _key: string;
    } & AvailabilityDuration
  >;
};

export type Availability = Array<
  {
    _key: string;
  } & AvailabilityDay
>;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VenueReference
  | ArtistReference
  | SanityImageAssetReference
  | Event
  | SanityImageCrop
  | SanityImageHotspot
  | Artist
  | Venue
  | Slug
  | AvailabilityDuration
  | AvailabilityDay
  | Availability
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/app/events/[slug]/page.tsx
// Variable: EVENT_QUERY
// Query: *[    _type == "event" &&    slug.current == $slug  ][0]{  ...,  "date": coalesce(date, now()),  "doorsOpen": coalesce(doorsOpen, 0),  headline->,  venue->}
export type EVENT_QUERY_RESULT = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  eventType?: "in-person" | "virtual";
  date: string;
  doorsOpen: number | 0;
  venue: {
    _id: string;
    _type: "venue";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    city?: string;
    country?: string;
  } | null;
  headline: {
    _id: string;
    _type: "artist";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    name?: string;
    description?: string;
    photo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  tickets?: string;
} | null;

// Source: ../web/src/app/page.tsx
// Variable: EVENTS_QUERY
// Query: *[  _type == "event"  && defined(slug.current)  && date > now()]|order(date asc){_id, name, slug, date}
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  date: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n    _type == "event" &&\n    slug.current == $slug\n  ][0]{\n  ...,\n  "date": coalesce(date, now()),\n  "doorsOpen": coalesce(doorsOpen, 0),\n  headline->,\n  venue->\n}': EVENT_QUERY_RESULT;
    '*[\n  _type == "event"\n  && defined(slug.current)\n  && date > now()\n]|order(date asc){_id, name, slug, date}': EVENTS_QUERY_RESULT;
  }
}
